[www]

user = www
group = www

listen = /var/run/php/$pool.sock

listen.owner = www
listen.group = www
listen.mode = 0660

pm = dynamic
pm.max_children = 25
pm.start_servers = 3
pm.min_spare_servers = 1
pm.max_spare_servers = 5

pm.process_idle_timeout = 10s;
pm.max_requests = 1000

pm.status_path = /$pool-status
pm.status_listen = /var/run/php/$pool-status.sock

;access.log = /var/log/php/$pool-access.log
access.format = "{\"timestamp\":\"%{%Y-%m-%dT%H:%M:%S%z}t\",\"method\":\"%{REQUEST_METHOD}e\",\"host\":\"%{HTTP_HOST}e\",\"request\":\"%{REQUEST_URI}e\",\"status\":\"%s\",\"duration\":%d,\"memory\":%M,\"cpu_usage\":{\"user\":%{user}C,\"system\":%{system}C,\"total\":%{total}C}}"

;slowlog = /var/log/php/$pool-slow.log
;request_slowlog_timeout = 10s
;request_slowlog_trace_depth = 20

;request_terminate_timeout = 0
;request_terminate_timeout_track_finished = no

php_admin_value[max_execution_time] = 60
