#SPDX-License-Identifier: MIT-0
namespace: witia
name: services
version: 1.0.0
readme: README.md

authors:
  - Mateusz Wiącek <wiacek.m@witia.com.pl>

description: Collection of services roles mainly focused on FreeBSD

license_file: 'LICENSE'

tags: ['freebsd']

repository: https://github.com/MatthewDruid/ansible-collection-witia-services
issues: https://github.com/MatthewDruid/ansible-collection-witia-services/issues

dependencies:
  "community.general": ">=13.4.0"
  "community.postgresql": ">=4.2.0,<5.0.0"

